#!/bin/sh

### BEGIN INIT INFO
# Provides:          process
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Should-Start:      winbindd
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: start Process winbind monitor
### END INIT INFO


PATH=/sbin:/bin:/usr/sbin:/usr/bin

DAEMON=/root/process.py
#PIDDIR=/var/run/samba
#WINBINDPID=$PIDDIR/winbindd.pid

# clear conflicting settings from the environment
#unset TMPDIR

# See if the daemon is there
#test -x $DAEMON || exit 0

#. /lib/lsb/init-functions

case "$1" in
	start)
		echo "Starting the Python process monitor for Winbind" "process"

		python /root/process.py & exit 0

		;;

	stop)
		echo "Stopping the Python process monitor for Winbind" "process"
	
		pkill -9 python

		;;

	restart|force-reload)
		$0 stop && sleep 2 && $0 start
		;;

	status)
		ps aux | grep process.py
		;;
	*)
		echo "Usage: /etc/init.d/process {start|stop|restart|force-reload|status}"
		exit 1
		;;
esac
